=== Menen21/Practica1DIS/DTD.dtd
<!ELEMENT Almacen (productos*, clientes*, pedidos*)>
	<!ELEMENT productos (producto*)>
	<!ELEMENT producto (codigo, nombre_producto, descripcion, stock, localizacion, pendientes_de_entrada)>
	<!ELEMENT codigo (#PCDATA)>
	<!ELEMENT nombre_producto (#PCDATA)>
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT stock (#PCDATA)>
	<!ELEMENT localizacion (pasillo, estanteria, estante)>
	<!ELEMENT pasillo (#PCDATA)>
	<!ELEMENT estanteria (#PCDATA)>
	<!ELEMENT estante (#PCDATA)>
	<!ELEMENT pendientes_de_entrada (#PCDATA)>
	<!ELEMENT clientes (cliente*)>
	<!ELEMENT cliente (nombre, apellidos, email, telefono, direccion)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT telefono (#PCDATA)>
	<!ELEMENT direccion (calle, numero_calle, cod_postal, poblacion, pais)>
	<!ELEMENT calle (#PCDATA)>
	<!ELEMENT numero_calle (#PCDATA)>
	<!ELEMENT cod_postal (#PCDATA)>
	<!ELEMENT poblacion (#PCDATA)>
	<!ELEMENT pais (#PCDATA)>
	<!ELEMENT pedidos (pedido*)>
	<!ELEMENT pedido (producto_pedido+, cantidad+, destinatario, direccion, fecha_entrega_estimada)>
	<!ELEMENT producto_pedido (#PCDATA)>
	<!ELEMENT cantidad (#PCDATA)>
	<!ELEMENT destinatario (#PCDATA)>
	<!ELEMENT fecha_entrega_estimada (#PCDATA)>

=== Menen21/Practica1DIS/almacen.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Example SYSTEM  "DTD.dtd">
<Almacen>
    <productos>
        <producto>
            <codigo>asdas</codigo>
            <nombre>sda</nombre>
            <descripcion>asd</descripcion>
            <stock>dsa</stock>
            <localizacion>
                <pasillo>das</pasillo>
                <estanteria>das</estanteria>
                <estante>das</estante>
            </localizacion>
            <pendiente>asd</pendiente>
        </producto>
        <producto>
            <codigo>l</codigo>
            <nombre>l</nombre>
            <descripcion>l</descripcion>
            <stock>l</stock>
            <localizacion>
                <pasillo>l</pasillo>
                <estanteria>l</estanteria>
                <estante>l</estante>
            </localizacion>
            <pendiente>l</pendiente>
        </producto>
        <producto>
            <codigo>4</codigo>
            <nombre>gfh</nombre>
            <descripcion>gfh</descripcion>
            <stock>ghf</stock>
            <localizacion>
                <pasillo>gf</pasillo>
                <estanteria>fgh</estanteria>
                <estante>fgh</estante>
            </localizacion>
            <pendiente>ghf</pendiente>
        </producto>
    </productos>
    <clientes>
        <cliente>
            <nombre>sda</nombre>
            <apellidos>asd</apellidos>
            <email>asd</email>
            <telefono>asd</telefono>
            <direccion>
                <calle>sda</calle>
                <numero_calle>sad</numero_calle>
                <cod_postal>asd</cod_postal>
                <poblacion>sda</poblacion>
                <pais>as</pais>
            </direccion>
        </cliente>
    </clientes>
    <pedidos>
        <pedido>
            <producto>sda</producto>
            <cantidad>das</cantidad>
            <direccion>
                <calle>sad</calle>
                <numero_calle>sad</numero_calle>
                <cod_postal>asd</cod_postal>
                <poblacion>sad</poblacion>
                <pais>asd</pais>
            </direccion>
            <fecha_entrega_estimada>sda</fecha_entrega_estimada>
        </pedido>
    </pedidos>
</Almacen>
