<!DOCTYPE Almacen [
	<!ELEMENT Almacen (PRODUCTO, CLIENTES, PEDIDOS) *>
	<!ELEMENT PRODUCTO (c贸digo, nombre, descripcion, stock, localizacion, pendientes)>
	<!ELEMENT c贸digo (#PCDATA)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT stock (#PCDATA)>
	<!ELEMENT localizacion (pasillo, estanteria, estante)>
	<!ELEMENT pasillo (#PCDATA)>
	<!ELEMENT estanteria (#PCDATA)>
	<!ELEMENT estante (#PCDATA)>
	<!ELEMENT pendientes (#PCDATA)>
	<!ELEMENT CLIENTES (nombre, apellidos, email, telf, direccion)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT telf (#PCDATA)>
	<!ELEMENT direccion (calle, numero, codPostal, poblacion, pais)>
	<!ELEMENT calle (#PCDATA)>
	<!ELEMENT numero (#PCDATA)>
	<!ELEMENT codPostal (#PCDATA)>
	<!ELEMENT poblacion (#PCDATA)>
	<!ELEMENT pais (#PCDATA)>
	<!ELEMENT PEDIDOS (productos, cantidad, dirEntrega, destinatario, fechaEntrega)>
	<!ELEMENT productos (#PCDATA)>
	<!ELEMENT cantidad (#PCDATA)>
	<!ELEMENT dirEntrega (calleP, numeroP, codPostalP, poblacionP, paisP)>
	<!ELEMENT calleP (#PCDATA)>
	<!ELEMENT numeroP (#PCDATA)>
	<!ELEMENT codPostalP (#PCDATA)>
	<!ELEMENT poblacionP (#PCDATA)>
	<!ELEMENT paisP (#PCDATA)>
	<!ELEMENT destinatario (#PCDATA)>
	<!ELEMENT fechaEntrega (#PCDATA)>
]>

<almacen>
	<producto>
		<c贸digo></c贸digo>
		<nombre></nombre>
		<descripcion></descripcion>
		<stock></stock>
		<localizacion>
			<pasillo></pasillo>
			<estanteria></estanteria>
			<estante></estante>
		</localizacion>
		<pendientes></pendientes>
	</producto>

	<clientes>
		<nombre></nombre>
		<apellidos></apellidos>
		<email></email>
		<telf></telf>
		<direccion>
			<calle></calle>
			<numero></numero>
			<codPostal></codPostal>
			<poblacion></poblacion>
			<pais></pais>
		</direccion>
	</clientes>

	<pedidos>
		<productos></productos>
		<cantidad></cantidad>
		<dirEntrega>
			<calleP></calleP>
			<numeroP></numeroP>
			<codPostalP></codPostalP>
			<poblacionP></poblacionP>
			<paisP></paisP>
		</dirEntrega>
		<destinatario></destinatario>
		<fechaEntrega></fechaEntrega>

</almacen>